menu:
  Home: /
  Archives: /archives
  Feed: /atom.xml

widgets:
  - search
  - tagcloud
  - links

excerpt_link: Read More

twitter:
  username:
  show_replies: false
  tweet_count: 5

addthis:
  enable: false
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

baidu_share:
  enable: true

fancybox: true

rss: /atom.xml

#comment_provider: facebook
## Facebook comment
#facebook:
#  appid: 123456789012345
#  comment_count: 5
#  comment_width: 840
#  comment_colorscheme: light
