categories: Categories
search: Search
tags: Tags
tagcloud: Tag Cloud
tweets: Tweets
prev: Prev
next: Next
prev_post: "Previous Post"
next_post: "Next Post"
comment: Comments
archives: Archives
archive_a: Archives
archive_b: "Archives: %s"
page: Page %d
page_total: "&nbsp(Total %d)"
recent_posts: Recent Posts
google: Google
baidu: Baidu
home: Home
feed: Feed
about: About
read_more: "Read More"
github: GitHub
