categories: Categories
search: Search
tags: Tags
tagcloud: Tag Cloud
tweets: Tweets
prev: Prev
next: Next
prev_post: Next
next_post: Prev
comment: Comments
duoshuo: Duoshuo
archive_a: Archives
archive_b: "Archives: %s"
page: Page %d
recent_posts: Recent Posts
google: Google
baidu: Baidu
